# Generated by Django 5.2.8 on 2025-11-09 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecosystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('climate', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecosystems/')),
                ('hologram_preview', models.URLField(blank=True, help_text='URL to hologram preview', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ecosystems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('habitat', models.CharField(max_length=200)),
                ('diet', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/')),
                ('hologram_preview', models.URLField(blank=True, help_text='URL to hologram preview', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecosystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='ecosystem.ecosystem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
