# Generated by Django 5.2.8 on 2025-11-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='conservation_status',
            field=models.CharField(blank=True, help_text='e.g., Endangered, Least Concern, Extinct', max_length=100),
        ),
        migrations.AddField(
            model_name='animal',
            name='species_type',
            field=models.CharField(choices=[('existing', 'Existing Species'), ('extinct', 'Extinct Species')], default='existing', max_length=20),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='era',
            field=models.CharField(choices=[('jurassic', 'Jurassic'), ('cretaceous', 'Cretaceous'), ('paleogene', 'Paleogene'), ('neogene', 'Neogene'), ('quaternary', 'Quaternary'), ('present', 'Present Day')], default='present', max_length=50),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='precipitation',
            field=models.CharField(blank=True, help_text='Annual precipitation', max_length=100),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='region',
            field=models.CharField(choices=[('amazon', 'Amazon Rainforest'), ('sahara', 'Sahara Desert'), ('arctic', 'Arctic Tundra'), ('coral', 'Coral Reef'), ('savanna', 'African Savanna'), ('taiga', 'Boreal Forest (Taiga)'), ('temperate', 'Temperate Forest'), ('ocean', 'Deep Ocean'), ('mountain', 'Mountain Range'), ('wetland', 'Wetland')], default='amazon', max_length=50),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='temperature_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='temperature_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ecosystem',
            name='vegetation',
            field=models.TextField(blank=True, help_text='Description of vegetation'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='hologram_preview',
            field=models.URLField(blank=True, help_text='URL to hologram preview or 3D model', null=True),
        ),
        migrations.AlterField(
            model_name='ecosystem',
            name='hologram_preview',
            field=models.URLField(blank=True, help_text='URL to hologram preview or 3D model', null=True),
        ),
    ]
