# Generated by Django 5.2.8 on 2025-11-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_animal_conservation_status_animal_species_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='hologram_preview',
        ),
        migrations.RemoveField(
            model_name='ecosystem',
            name='hologram_preview',
        ),
    ]
