# Generated by Django 5.2.8 on 2025-11-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalsession',
            name='lesson_content',
            field=models.TextField(blank=True, help_text='Additional lesson content/notes'),
        ),
        migrations.AddField(
            model_name='educationalsession',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video recording (YouTube, Vimeo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='educationalsession',
            name='hologram_preview',
            field=models.URLField(blank=True, help_text='URL to hologram preview or 3D model', null=True),
        ),
        migrations.CreateModel(
            name='SessionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='educational_sessions.educationalsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(blank=True, max_length=200)),
                ('option_d', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='educational_sessions.educationalsession')),
            ],
            options={
                'verbose_name_plural': 'Session Quizzes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='PDF, notes, or other downloadable files', upload_to='session_resources/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='educational_sessions.educationalsession')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
