# Generated by Django 5.2.8 on 2025-11-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_sessions', '0002_educationalsession_lesson_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalsession',
            name='hologram_preview',
        ),
    ]
