# Generated by Django 5.2.8 on 2025-11-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecosystem', '0002_animal_conservation_status_animal_species_type_and_more'),
        ('educational_sessions', '0002_educationalsession_lesson_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Time spent viewing in minutes')),
                ('completed', models.BooleanField(default=False)),
                ('ecosystem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_visits', to='ecosystem.ecosystem')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_watches', to='educational_sessions.educationalsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('student', 'ecosystem'), ('student', 'session')},
            },
        ),
    ]
